#!/usr/bin/env python3

import argparse
import os
import subprocess

print("Indexing...")

# The number of CPU cores available
cores = os.cpu_count()

parser = argparse.ArgumentParser()
parser.add_argument("collection", nargs=1)

args = parser.parse_args()

for collection in args.collection.split(","):
    subprocess.run("java -cp anserini.jar io.anserini.index.IndexCollection -collection TrecCollection -generator JsoupGenerator -threads {0} -input /input/collections/{1} -index {1} -storePositions -storeDocvectors -storeRawDocs".format(cores, args.collection).split())
