#!/usr/bin/env python3

import argparse
import subprocess

print("Searching...")

parser = argparse.ArgumentParser()
parser.add_argument("topic", nargs=1)
parser.add_argument("topic_format", nargs=1)

args = parser.parse_args()

subprocess.run("java -cp anserini.jar io.anserini.search.SearchCollection -topicreader Trec -index index -topics /input/topics/{} -output /output/run.robust04.bm25.topics.robust04.301-450.601-700.txt -bm25".format(args.topic).split())
subprocess.run("java -cp anserini.jar io.anserini.search.SearchCollection -topicreader Trec -index index -topics /input/topics/{} -output /output/run.robust04.bm25+rm3.topics.robust04.301-450.601-700.txt -bm25 -rm3".format(args.topic).split())
subprocess.run("java -cp anserini.jar io.anserini.search.SearchCollection -topicreader Trec -index index -topics /input/topics/{} -output /output/run.robust04.bm25+ax.topics.robust04.301-450.601-700.txt -bm25 -axiom -rerankCutoff 20 -axiom.deterministic".format(args.topic).split())
subprocess.run("java -cp anserini.jar io.anserini.search.SearchCollection -topicreader Trec -index index -topics /input/topics/{} -output /output/run.robust04.ql.topics.robust04.301-450.601-700.txt -ql".format(args.topic).split())
subprocess.run("java -cp anserini.jar io.anserini.search.SearchCollection -topicreader Trec -index index -topics /input/topics/{} -output /output/run.robust04.ql+rm3.topics.robust04.301-450.601-700.txt -ql -rm3".format(args.topic).split())
subprocess.run("java -cp anserini.jar io.anserini.search.SearchCollection -topicreader Trec -index index -topics /input/topics/{} -output /output/run.robust04.ql+ax.topics.robust04.301-450.601-700.txt -ql -axiom -rerankCutoff 20 -axiom.deterministic".format(args.topic).split())
